services:
  orchestrator:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: orchestrator
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - app-data:/app/data
    restart: unless-stopped

volumes:
  app-data:
